//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academicians
    {
        public int id { get; set; }
        public string Full_name { get; set; }
        public Nullable<System.DateTime> Date_Birth { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> Year_ZOV { get; set; }
    }
}
