//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals_Kamalov
    {
        public int ID_Jivotnoe { get; set; }
        public string Name { get; set; }
        public string Otryad { get; set; }
    }
}
