//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enginer
    {
        public int Id_eng { get; set; }
        public string Speciality_en { get; set; }
        public Nullable<int> Tab_number { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
