//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exsamen
    {
        public int Id_exam { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Kod { get; set; }
        public Nullable<int> Reg_number { get; set; }
        public Nullable<int> Tab_number { get; set; }
        public string Kabinet { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
