//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Study_Baza : DbContext
    {
        public Study_Baza()
            : base("name=Study_Baza")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academicians> Academicians { get; set; }
        public virtual DbSet<Animals_Kamalov> Animals_Kamalov { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Countries_Kamalov> Countries_Kamalov { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Enginer> Enginer { get; set; }
        public virtual DbSet<Exsamen> Exsamen { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Flowers_Kamalov> Flowers_Kamalov { get; set; }
        public virtual DbSet<Gimnazisti> Gimnazisti { get; set; }
        public virtual DbSet<Kafedra> Kafedra { get; set; }
        public virtual DbSet<Management_Kamalov> Management_Kamalov { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Ucheniki> Ucheniki { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<Zav_kaf> Zav_kaf { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
    }
}
