//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucheniki
    {
        public int ID { get; set; }
        public string Familiya { get; set; }
        public string Predmet { get; set; }
        public string Shkola { get; set; }
        public Nullable<decimal> Bally { get; set; }
    }
}
