//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_Kamalov_wpf_320P.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public string ID_zayavka { get; set; }
        public Nullable<int> Kod { get; set; }
        public string Number_zayavka { get; set; }
    
        public virtual Discipline Discipline { get; set; }
    }
}
